const roles = {
    1: 'WO Stock Master',
    2: 'WO Shipment Received',
    3: 'WO Dispatching',
    4: 'WO Warehouse Location',
    5: 'WO Journal Movement',
    6: 'WO Journal ProfitLoss',
    7: 'WO Journal Counting',
    8: 'WO Return Sales Order',
    9: 'WO WMS Inventory',
    10: 'WO PutAway',
    11: 'WO Picking',
    12: 'WO Pallets',
    13: 'WO Mapped Items',
    14: 'WO Re-Allocation Picked',
    15: 'WO Bin to Bin History',
    16: 'WO Pick List Assigned',
    17: 'WO Physical Count',
    18: 'Axapta Inventory Items',
    19: 'Axapta Goods Receipts',
    20: 'Axapta Expected Shipments',
    21: 'Axapta Expected Transfer Orders',
    22: 'Axapta Items for Dispatch',
    23: 'Axapta Internal Transfer',
    24: 'Axapta Pick List',
    25: 'Axapta Journal List',
    26: 'Axapta Sales Picking List',
    27: 'Axapta Return Sales Order',
    28: 'Axapta Journal Profit Loss',
    29: 'Axapta Journal Movement',
    30: 'Axapta Journal Counting',
    31: 'WMS Goods Receiving',
    32: 'WMS Bin to Bin(Axapta',
    33: 'WMS Bin to Bin(Internal)',
    34: 'WMS Bin to Bin(Journal)',
    35: 'WMS Item Re Allocation',
    36: 'WMS WMS Inventory',
    37: 'WMS Physical Inventory',
    38: 'WMS Inventory by Bin Location',
    39: 'WMS WMS Inventory by Bin',
    40: 'WMS Put-Away Transaction',
    41: 'WMS Product Barcode Mapping',
    42: 'WMS Printing Pallets',
    43: 'WMS Dispatching',
    44: 'WMS Picking Slip',
    45: 'WMS Return RMA',
    46: 'WMS RMA Put-Away',
    47: 'WMS Journal Movement Counting',
    48: 'WMS Profit and Loss',
    49: 'WMS Cycle Counting',
    50: 'Settings',
    51: 'Admin',
};

export default roles;
